### ISSUE TITLE
UI2 checklist

### ISSUE THREAD

**Issue by mikesteele** [mikesteele/dual-captions#34]
On branch `ui2-localized`

- [x] React
- [x] Localized
- [x] Redux?
- [x] Persistent state, stored in chrome.storage
- [x] Extra space setting
- [ ] Remove original caption setting
- [x] Help page
- [x] Sites page
- [ ] Language options are in own language ("French" -> "Français")

Translations added for
- [x] English
- [x] French
- [ ] Spanish
- [ ] Portuguese 
- [ ] Russian
- [ ] Korean
